<?php

namespace Database\Seeders;

use Customer\Infrastructure\Persistence\Models\CustomerEloquentModel;
use Illuminate\Database\Seeder;

class RepresentativeCustomersSeeder extends Seeder
{
    /**
     * Liste de 50 clients représentatifs du panel cycliste avec diversité
     */
    public function run(): void
    {
        $this->command->info('Seeding representative customers...');

        // Nettoyer les clients existants du seeder (optionnel)
        CustomerEloquentModel::where('email', 'like', '%@example.com')->delete();

        $customers = [
            // VTTistes Trail/Enduro (10 clients)
            [
                'first_name' => 'Youssef',
                'last_name' => 'Ben Amar',
                'email' => 'youssef.benamar@example.com',
                'phone' => '+33612345001',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456001',
                'height' => 198,
                'weight' => 92,
                'address' => '12 rue des Alpes, 74000 Annecy',
                'notes' => 'VTT Enduro - Niveau expert - Préfère les descentes techniques',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Mei',
                'last_name' => 'Zhang',
                'email' => 'mei.zhang@example.com',
                'phone' => '+33612345002',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456002',
                'height' => 152,
                'weight' => 47,
                'address' => '45 avenue du Mont-Blanc, 74000 Annecy',
                'notes' => 'VTT Trail - Niveau intermédiaire - Sorties weekend',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Kofi',
                'last_name' => 'Mensah',
                'email' => 'kofi.mensah@example.com',
                'phone' => '+33612345003',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456003',
                'height' => 189,
                'weight' => 85,
                'address' => '8 chemin des Crêtes, 05000 Gap',
                'notes' => 'VTT All-Mountain - Expert - Compétitions régionales',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Sakura',
                'last_name' => 'Tanaka',
                'email' => 'sakura.tanaka@example.com',
                'phone' => '+33612345004',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456004',
                'height' => 158,
                'weight' => 51,
                'address' => '23 rue du Bike Park, 38000 Grenoble',
                'notes' => 'VTT Trail - Débutante - Première saison',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Amadou',
                'last_name' => 'Diallo',
                'email' => 'amadou.diallo@example.com',
                'phone' => '+33612345005',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456005',
                'height' => 195,
                'weight' => 88,
                'address' => '67 boulevard des Trails, 74000 Annecy',
                'notes' => 'VTT Enduro - Niveau confirmé - Préfère suspensions longues',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Priya',
                'last_name' => 'Sharma',
                'email' => 'priya.sharma@example.com',
                'phone' => '+33612345006',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456006',
                'height' => 163,
                'weight' => 54,
                'address' => '15 impasse du Single, 38000 Grenoble',
                'notes' => 'VTT XC - Compétitrice - Marathons VTT',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Carlos',
                'last_name' => 'Rodriguez',
                'email' => 'carlos.rodriguez@example.com',
                'phone' => '+33612345007',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456007',
                'height' => 172,
                'weight' => 68,
                'address' => '34 route des Sommets, 05000 Gap',
                'notes' => 'VTT Trail - Expert - Guides occasionnellement',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Aisha',
                'last_name' => 'Hassan',
                'email' => 'aisha.hassan@example.com',
                'phone' => '+33612345008',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456008',
                'height' => 168,
                'weight' => 59,
                'address' => '89 chemin des Bikers, 74000 Annecy',
                'notes' => 'VTT All-Mountain - Intermédiaire - Weekends longs',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Lars',
                'last_name' => 'Andersen',
                'email' => 'lars.andersen@example.com',
                'phone' => '+33612345009',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456009',
                'height' => 203,
                'weight' => 105,
                'address' => '56 avenue des Descentes, 38000 Grenoble',
                'notes' => 'VTT DH - Expert - Bike park uniquement',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Fatima',
                'last_name' => 'El Idrissi',
                'email' => 'fatima.elidrissi@example.com',
                'phone' => '+33612345010',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456010',
                'height' => 149,
                'weight' => 45,
                'address' => '12 rue des Pistes, 05000 Gap',
                'notes' => 'VTT XC - Confirmée - Course XC Marathon',
                'is_risky' => false,
            ],

            // Routiers (10 clients)
            [
                'first_name' => 'Jean-Pierre',
                'last_name' => 'Lefebvre',
                'email' => 'jeanpierre.lefebvre@example.com',
                'phone' => '+33612345011',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456011',
                'height' => 176,
                'weight' => 68,
                'address' => '23 avenue des Cols, 06000 Nice',
                'notes' => 'Route - Expert - Cyclosportives longue distance',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Nguyen',
                'last_name' => 'Thi Mai',
                'email' => 'nguyen.thimai@example.com',
                'phone' => '+33612345012',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456012',
                'height' => 155,
                'weight' => 48,
                'address' => '45 rue du Peloton, 13000 Marseille',
                'notes' => 'Route - Confirmée - Sorties club hebdomadaires',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Dimitri',
                'last_name' => 'Volkov',
                'email' => 'dimitri.volkov@example.com',
                'phone' => '+33612345013',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456013',
                'height' => 192,
                'weight' => 78,
                'address' => '78 boulevard des Cyclistes, 06000 Nice',
                'notes' => 'Route - Expert - Ancienne licence compétition',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Ines',
                'last_name' => 'Silva',
                'email' => 'ines.silva@example.com',
                'phone' => '+33612345014',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456014',
                'height' => 162,
                'weight' => 52,
                'address' => '34 chemin des Grimpeurs, 04000 Digne-les-Bains',
                'notes' => 'Route - Intermédiaire - Préfère la montagne',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Mohammed',
                'last_name' => 'Al-Rashid',
                'email' => 'mohammed.alrashid@example.com',
                'phone' => '+33612345015',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456015',
                'height' => 181,
                'weight' => 73,
                'address' => '56 avenue des Sommets, 06000 Nice',
                'notes' => 'Route - Expert - Spécialiste cols alpins',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Yuki',
                'last_name' => 'Nakamura',
                'email' => 'yuki.nakamura@example.com',
                'phone' => '+33612345016',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456016',
                'height' => 145,
                'weight' => 42,
                'address' => '12 rue des Cyclotouristes, 13000 Marseille',
                'notes' => 'Route - Débutante - Première année',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Antonio',
                'last_name' => 'Ferreira',
                'email' => 'antonio.ferreira@example.com',
                'phone' => '+33612345017',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456017',
                'height' => 174,
                'weight' => 70,
                'address' => '89 boulevard du Velodrome, 06000 Nice',
                'notes' => 'Route - Confirmé - Sorties 100-150km',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Leila',
                'last_name' => 'Kaddour',
                'email' => 'leila.kaddour@example.com',
                'phone' => '+33612345018',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456018',
                'height' => 171,
                'weight' => 62,
                'address' => '23 allée des Sprinters, 13000 Marseille',
                'notes' => 'Route - Confirmée - Licence compétition loisir',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Thomas',
                'last_name' => 'O\'Connor',
                'email' => 'thomas.oconnor@example.com',
                'phone' => '+33612345019',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456019',
                'height' => 186,
                'weight' => 81,
                'address' => '45 rue des Ascensions, 04000 Digne-les-Bains',
                'notes' => 'Route - Expert - Cyclosportives haut niveau',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Camila',
                'last_name' => 'Gonzalez',
                'email' => 'camila.gonzalez@example.com',
                'phone' => '+33612345020',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456020',
                'height' => 166,
                'weight' => 58,
                'address' => '67 chemin des Montées, 06000 Nice',
                'notes' => 'Route - Intermédiaire - Sorties plaisir weekend',
                'is_risky' => false,
            ],

            // Triathlètes (8 clients)
            [
                'first_name' => 'Kwame',
                'last_name' => 'Owusu',
                'email' => 'kwame.owusu@example.com',
                'phone' => '+33612345021',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456021',
                'height' => 188,
                'weight' => 82,
                'address' => '12 avenue des Triathlètes, 06000 Nice',
                'notes' => 'Triathlon - Ironman - Format longue distance',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Hana',
                'last_name' => 'Kim',
                'email' => 'hana.kim@example.com',
                'phone' => '+33612345022',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456022',
                'height' => 160,
                'weight' => 53,
                'address' => '34 rue du Half-Ironman, 34000 Montpellier',
                'notes' => 'Triathlon - Half distance - Compétitions régionales',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Rashid',
                'last_name' => 'Ndiaye',
                'email' => 'rashid.ndiaye@example.com',
                'phone' => '+33612345023',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456023',
                'height' => 196,
                'weight' => 89,
                'address' => '56 boulevard des Finishers, 34000 Montpellier',
                'notes' => 'Triathlon - Format olympique - Multisports',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Ananya',
                'last_name' => 'Patel',
                'email' => 'ananya.patel@example.com',
                'phone' => '+33612345024',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456024',
                'height' => 157,
                'weight' => 49,
                'address' => '78 allée des Sprint, 06000 Nice',
                'notes' => 'Triathlon - Sprint distance - Débutante triathlon',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Sven',
                'last_name' => 'Johansson',
                'email' => 'sven.johansson@example.com',
                'phone' => '+33612345025',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456025',
                'height' => 194,
                'weight' => 86,
                'address' => '23 chemin des Transitions, 34000 Montpellier',
                'notes' => 'Triathlon - Ironman 70.3 - Entraînement intensif',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Zara',
                'last_name' => 'Mohamed',
                'email' => 'zara.mohamed@example.com',
                'phone' => '+33612345026',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456026',
                'height' => 165,
                'weight' => 57,
                'address' => '45 rue du Contre-la-montre, 06000 Nice',
                'notes' => 'Triathlon - Format M - Club triathlon local',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Ravi',
                'last_name' => 'Singh',
                'email' => 'ravi.singh@example.com',
                'phone' => '+33612345027',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456027',
                'height' => 179,
                'weight' => 74,
                'address' => '67 avenue des Kilomètres, 34000 Montpellier',
                'notes' => 'Triathlon - Longue distance - 15 Ironman finis',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Sofia',
                'last_name' => 'Kowalski',
                'email' => 'sofia.kowalski@example.com',
                'phone' => '+33612345028',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456028',
                'height' => 169,
                'weight' => 60,
                'address' => '89 boulevard des Athlètes, 06000 Nice',
                'notes' => 'Triathlon - Format XS et S - Première saison',
                'is_risky' => false,
            ],

            // Gravellistes (8 clients)
            [
                'first_name' => 'Jamal',
                'last_name' => 'Benali',
                'email' => 'jamal.benali@example.com',
                'phone' => '+33612345029',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456029',
                'height' => 175,
                'weight' => 71,
                'address' => '12 rue des Chemins, 84000 Avignon',
                'notes' => 'Gravel - Bikepacking - Voyages longue durée',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Ling',
                'last_name' => 'Chen',
                'email' => 'ling.chen@example.com',
                'phone' => '+33612345030',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456030',
                'height' => 148,
                'weight' => 44,
                'address' => '34 chemin des Graviers, 26000 Valence',
                'notes' => 'Gravel - Aventure - Sorties exploratoires',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Mateo',
                'last_name' => 'Sanchez',
                'email' => 'mateo.sanchez@example.com',
                'phone' => '+33612345031',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456031',
                'height' => 191,
                'weight' => 84,
                'address' => '56 avenue des Pistes, 84000 Avignon',
                'notes' => 'Gravel - Course - Compétitions gravel endurance',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Noor',
                'last_name' => 'Al-Mansoori',
                'email' => 'noor.almansoori@example.com',
                'phone' => '+33612345032',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456032',
                'height' => 172,
                'weight' => 63,
                'address' => '78 rue du Tout-Terrain, 26000 Valence',
                'notes' => 'Gravel - Polyvalente - Route et chemins',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Olaf',
                'last_name' => 'Nielsen',
                'email' => 'olaf.nielsen@example.com',
                'phone' => '+33612345033',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456033',
                'height' => 207,
                'weight' => 115,
                'address' => '23 allée des Sentiers, 84000 Avignon',
                'notes' => 'Gravel - Cyclo-cross - Hiver principalement',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Amara',
                'last_name' => 'Keita',
                'email' => 'amara.keita@example.com',
                'phone' => '+33612345034',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456034',
                'height' => 168,
                'weight' => 60,
                'address' => '45 chemin de Traverse, 26000 Valence',
                'notes' => 'Gravel - Loisir - Weekends découverte',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Hiroshi',
                'last_name' => 'Yamamoto',
                'email' => 'hiroshi.yamamoto@example.com',
                'phone' => '+33612345035',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456035',
                'height' => 169,
                'weight' => 64,
                'address' => '67 route des Aventures, 84000 Avignon',
                'notes' => 'Gravel - Ultra-distance - Événements 200km+',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Esther',
                'last_name' => 'Van der Berg',
                'email' => 'esther.vanderberg@example.com',
                'phone' => '+33612345036',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456036',
                'height' => 170,
                'weight' => 62,
                'address' => '89 boulevard des Virages, 26000 Valence',
                'notes' => 'Gravel - Débutante - Transition du route',
                'is_risky' => false,
            ],

            // Cyclotouristes et Loisir (8 clients)
            [
                'first_name' => 'Claude',
                'last_name' => 'Dubois',
                'email' => 'claude.dubois@example.com',
                'phone' => '+33612345037',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456037',
                'height' => 173,
                'weight' => 98,
                'address' => '12 rue Tranquille, 33000 Bordeaux',
                'notes' => 'Cyclotourisme - Balade - Sorties familiales',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Thanh',
                'last_name' => 'Nguyen',
                'email' => 'thanh.nguyen@example.com',
                'phone' => '+33612345038',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456038',
                'height' => 151,
                'weight' => 46,
                'address' => '34 avenue Douce, 33000 Bordeaux',
                'notes' => 'Loisir - Santé - 2-3 sorties par semaine',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Ibrahim',
                'last_name' => 'Traoré',
                'email' => 'ibrahim.traore@example.com',
                'phone' => '+33612345039',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456039',
                'height' => 183,
                'weight' => 76,
                'address' => '56 chemin des Vignes, 33000 Bordeaux',
                'notes' => 'Cyclotourisme - Randonneur - Voyages à vélo',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Valentina',
                'last_name' => 'Rossi',
                'email' => 'valentina.rossi@example.com',
                'phone' => '+33612345040',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456040',
                'height' => 165,
                'weight' => 61,
                'address' => '78 rue des Balades, 33000 Bordeaux',
                'notes' => 'Loisir - Débutante - Vélo plaisir',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Khalil',
                'last_name' => 'Hamza',
                'email' => 'khalil.hamza@example.com',
                'phone' => '+33612345041',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456041',
                'height' => 170,
                'weight' => 75,
                'address' => '23 allée Paisible, 33000 Bordeaux',
                'notes' => 'Cyclotourisme - Club FFCT - Sorties organisées',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Ayumi',
                'last_name' => 'Sato',
                'email' => 'ayumi.sato@example.com',
                'phone' => '+33612345042',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456042',
                'height' => 143,
                'weight' => 43,
                'address' => '45 chemin Bucolique, 33000 Bordeaux',
                'notes' => 'Loisir - Retraite active - Vélo santé',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Henrique',
                'last_name' => 'Costa',
                'email' => 'henrique.costa@example.com',
                'phone' => '+33612345043',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456043',
                'height' => 174,
                'weight' => 80,
                'address' => '67 route des Découvertes, 33000 Bordeaux',
                'notes' => 'Cyclotourisme - Longues randonnées - Parcours patrimoniaux',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Malika',
                'last_name' => 'Ouedraogo',
                'email' => 'malika.ouedraogo@example.com',
                'phone' => '+33612345044',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456044',
                'height' => 163,
                'weight' => 62,
                'address' => '89 boulevard Calme, 33000 Bordeaux',
                'notes' => 'Loisir - Balade - Véloroutes et voies vertes',
                'is_risky' => false,
            ],

            // Débutants variés (4 clients)
            [
                'first_name' => 'Hugo',
                'last_name' => 'Dufour',
                'email' => 'hugo.dufour@example.com',
                'phone' => '+33612345045',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456045',
                'height' => 178,
                'weight' => 74,
                'address' => '12 rue des Novices, 69000 Lyon',
                'notes' => 'Débutant - Route - Première location pour essai',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Keiko',
                'last_name' => 'Watanabe',
                'email' => 'keiko.watanabe@example.com',
                'phone' => '+33612345046',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456046',
                'height' => 135,
                'weight' => 42,
                'address' => '34 avenue des Débuts, 69000 Lyon',
                'notes' => 'Débutante - VTT - Découverte activité',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Abdel',
                'last_name' => 'Bennani',
                'email' => 'abdel.bennani@example.com',
                'phone' => '+33612345047',
                'identity_document_type' => 'passport',
                'identity_document_number' => 'FR123456047',
                'height' => 180,
                'weight' => 76,
                'address' => '56 chemin des Premiers Pas, 69000 Lyon',
                'notes' => 'Débutant - Gravel - Transition running vers vélo',
                'is_risky' => false,
            ],
            [
                'first_name' => 'Elena',
                'last_name' => 'Popescu',
                'email' => 'elena.popescu@example.com',
                'phone' => '+33612345048',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456048',
                'height' => 164,
                'weight' => 56,
                'address' => '78 rue des Apprentis, 69000 Lyon',
                'notes' => 'Débutante - Route - Remise en forme',
                'is_risky' => false,
            ],

            // Clients risqués (2 clients)
            [
                'first_name' => 'Dylan',
                'last_name' => 'Roussel',
                'email' => 'dylan.roussel@example.com',
                'phone' => '+33612345049',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456049',
                'height' => 183,
                'weight' => 85,
                'address' => '12 rue Problématique, 75001 Paris',
                'notes' => 'ATTENTION : Retards répétés sur locations précédentes',
                'is_risky' => true,
            ],
            [
                'first_name' => 'Samira',
                'last_name' => 'Aziz',
                'email' => 'samira.aziz@example.com',
                'phone' => '+33612345050',
                'identity_document_type' => 'id_card',
                'identity_document_number' => 'FR123456050',
                'height' => 169,
                'weight' => 61,
                'address' => '34 avenue Litigieuse, 75001 Paris',
                'notes' => 'ATTENTION : Vélo rendu en mauvais état lors location précédente',
                'is_risky' => true,
            ],
        ];

        $count = 0;
        foreach ($customers as $customerData) {
            CustomerEloquentModel::create($customerData);
            $count++;
            $this->command->info("✓ Created: {$customerData['first_name']} {$customerData['last_name']} - {$customerData['height']}cm / {$customerData['weight']}kg");
        }

        $this->command->info("✓ Successfully seeded {$count} representative customers!");
        $this->command->info("Height range: 135cm - 207cm | Weight range: 42kg - 115kg");
    }
}
